
import Link from 'next/link';
export default function Home(){
  return (
    <main className="min-h-screen bg-[#FFFEF9]">
      <header className="sticky top-0 bg-[#FFFEF9]/80 backdrop-blur border-b border-black/5 z-20"><div className="max-w-[1200px] mx-auto px-6 h-[56px] flex justify-between items-center"><p className="font-serif font-bold">ILQ • Institut Ludopédagogique</p><nav className="flex gap-4 text-[11px] uppercase"><Link href="/dashboard" className="opacity-60 hover:opacity-100">SuperAdmin</Link><Link href="/board/ILQ-TEST01" className="opacity-60 hover:opacity-100">Facilitateur</Link><Link href="/play/ILQ-TEST01" className="opacity-60 hover:opacity-100">Joueur</Link></nav></div></header>
      <section className="max-w-[1200px] mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12">
        <div><p className="text-[11px] uppercase tracking-widest opacity-50">Atelier-jeu sérieux 45-180 min • Double lecture</p><h1 className="font-serif text-[72px] leading-[0.85] mt-4">ANGLE<br/>MORT</h1><p className="font-serif text-[24px] mt-4">Le jeu qui révèle ce qu'on ne voit pas</p><p className="mt-6 leading-[1.6] opacity-80 max-w-[520px]">Gameplay complet: Signal doré → Indice1 → débat rester/bouger → Indice2 → vote Punctum avec jetons (8 emplacements Signal/Situation) → carte ALL niveau 1-3. 75 cartes REC/MIC/PRI/CLI, 4 espaces avec rétine centrale.</p><div className="mt-8 flex gap-3"><Link href="/board/ILQ-TEST01" className="bg-black text-white px-6 py-3 rounded-full text-[13px]">Lancer Board Test Gameplay</Link><Link href="/dashboard" className="border px-6 py-3 rounded-full text-[13px]">Dashboard + Guides</Link></div></div>
        <div className="rounded-[24px] border bg-white p-3 shadow"><div className="aspect-square rounded-[16px] bg-[#FFFEFB] border grid grid-cols-2 grid-rows-2 relative overflow-hidden"><div className="absolute left-1/2 top-0 bottom-0 w-px bg-black/10" /><div className="absolute top-1/2 left-0 right-0 h-px bg-black/10" /><div className="p-4"><p className="text-[9px] uppercase opacity-40">N-O S1 Blanc</p><p className="font-bold">Inclusion</p></div><div className="p-4 border-l text-right"><p className="text-[9px] uppercase opacity-40">N-E S2 Rouge</p><p className="font-bold">Hors champ</p></div><div className="p-4 border-t"><p className="text-[9px] uppercase opacity-40">S-O non-S2 Jaune</p><p className="font-bold">Tolérance</p></div><div className="p-4 border-l border-t text-right bg-black/[0.02]"><p className="text-[9px] uppercase opacity-40">S-E non-S1 Violet</p><p className="font-bold">Façade</p></div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black border-4 border-white shadow flex items-center justify-center"><div className="w-3 h-3 rounded-full bg-white/90" /></div></div><p className="text-[11px] mt-3 opacity-60">Plateau Punctum avec rétine centrale - 8 emplacements par zone</p></div>
      </section>
    </main>
  )
}
